[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
gloo-net = { version = "0.2.4", default-features = false, features = ["futures-core", "futures-sink", "http", "json", "serde", "serde_json", "pin-project"] }
wasm-bindgen-futures = "0.4.33"
wasm-bindgen = { version = "0.2.84", default-features = false, features = ["std"] }
yew = { git = "https://github.com/yewstack/yew.git", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }
shared_data = { path = "../shared_data" }
web-sys = { version = "0.3.60", features = ["Window", "DragEvent", "DataTransfer", "FileList", "HtmlDocument", "HtmlButtonElement"] }
gloo-console = "0.2.3"
chrono = { version = "0.4.23", default-features = false, features = ["alloc"] }
js-sys = "0.3.60"
gloo-utils = { version = "0.1.6", default-features = false }
base64 = "0.20.0"
