[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-net = { version = "0.4.0", default-features = false, features = ["futures-core", "futures-sink", "http", "json", "serde", "serde_json", "pin-project"] }
wasm-bindgen-futures = "0.4.37"
wasm-bindgen = { version = "0.2.87", default-features = false, features = ["std"] }
yew = { version = "0.21.0", features = ["csr"] }
yew-router = { version = "0.18.0" }
shared_data = { path = "../shared_data" }
web-sys = { version = "0.3.64", features = ["Window", "DragEvent", "DataTransfer", "FileList", "HtmlDocument", "HtmlButtonElement", "Blob"] }
gloo-console = "0.3.0"
chrono = { version = "0.4.31", default-features = false, features = ["alloc"] }
js-sys = "0.3.64"
gloo-utils = { version = "0.2.0", default-features = false }
base64 = "0.20.0"
