[workspace]
members = ["backend", "frontend", "shared_data"]
resolver = "2"

[profile.production]
inherits = "release"
opt-level = 2
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.release]
panic = "abort"
lto = "fat"
opt-level = "s"
codegen-units = 1
