[package]
name = "shared_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.147", features = ["serde_derive"] }
serde_json = "1.0.89"
sqlx = { version = "0.6.2", features = ["postgres", "runtime-tokio-rustls"], optional = true }

[features]
sqlx = ["dep:sqlx"]
