[package]
name = "shared_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.147", default-features = false,  features = ["serde_derive"] }
serde_json = { version = "1.0.89", default-features = false, features = ["alloc"] }
sqlx = { version = "0.6.2", default-features = false, features = ["macros", "postgres", "runtime-tokio-rustls"], optional = true }

[features]
sqlx = ["dep:sqlx"]
