name: CD

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  upload:
    environment: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Install wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install trunk
      - name: Build backend
        run: cargo build --profile production --bin backend
      - name: Build frontend
        run: "cd frontend && trunk build --release"
      - name: SCP files 
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "frontend/dist/*,backend/production/backend"
          target: /home/junkie/server_files
