name: CI

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown, x86_64-unknown-linux-gnu
          toolchain: nightly
      - name: Install cargo-leptos
        run: curl --proto '=https' --tlsv1.2 -LsSf https://leptos-rs.artifacts.axodotdev.host/cargo-leptos/v0.2.26/cargo-leptos-installer.sh | sh
      - name: Build backend
        run: cargo leptos build --release
      - name: Stop currently-running backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            sudo /usr/bin/systemctl stop itsjunetime.service
            rm /home/junkie/server_files/frontend* 2>/dev/null || :
      - name: SCP files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: "target/production/backend,frontend/dist/*,target/site/pkg/*"
          target: /home/junkie/server_files/
          strip_components: 2
          overwrite: true
      - name: Restart server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            sudo /usr/bin/systemctl daemon-reload
            sudo /usr/bin/systemctl start itsjunetime.service
            sudo /usr/sbin/nginx -s reload
