name: CI

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Install wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install trunk
      - name: Build backend
        run: cargo build --profile production --bin backend
      - name: Build frontend
        run: "cd frontend && trunk build --release"
      - name: Stop currently-running backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: sudo /usr/bin/systemctl stop itsjunetime.service
      - name: SCP files 
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/production/backend,frontend/dist/*"
          target: /home/junkie/server_files/
          strip_components: 2
          overwrite: true
      - name: Restart server 
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo /usr/bin/systemctl daemon-reload
            sudo /usr/bin/systemctl start itsjunetime.service
			sudo /usr/sbin/nginx -s reload
