name: CI

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: [wasm32-unknown-unknown, x86_64-unknown-linux-gnu]
      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'
      - name: Install wasm-opt
        run: "curl -L -o binaryen.tar.gz https://github.com/WebAssembly/binaryen/releases/download/version_117/binaryen-version_117-x86_64-linux.tar.gz && tar -xzvf ./binaryen.tar.gz"
      - name: Build backend
        run: cargo build --profile production --bin backend
      - name: Build frontend
        run: "cd frontend && trunk build --release"
      - name: Optimise wasm
        run: "cd frontend/dist && ../../binaryen-version_117/bin/wasm-opt -Oz -o opt.wasm $(ls frontend*.wasm) && mv ./opt.wasm $(ls frontend*.wasm)"
      - name: Stop currently-running backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo /usr/bin/systemctl stop itsjunetime.service
            rm /home/junkie/server_files/frontend* 2>/dev/null || :
      - name: SCP files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/production/backend,frontend/dist/*"
          target: /home/junkie/server_files/
          strip_components: 2
          overwrite: true
      - name: Restart server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo /usr/bin/systemctl daemon-reload
            sudo /usr/bin/systemctl start itsjunetime.service
            sudo /usr/sbin/nginx -s reload
